server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
          filters:
            - AddResponseHeader=X-Gateway,Activity5
            - AddRequestHeader=X-Gateway,Activity5

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
          filters:
            - AddResponseHeader=X-Gateway,Activity5
            - AddRequestHeader=X-Gateway,Activity5

      default-filters:
        - AddResponseHeader=X-Env,Activity5

eureka:
  client:
    service-url:
      defaultZone: http://api-gateway:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,configprops

info:
  app:
    name: api-gateway
    description: Spring Cloud API gateway
    version: 0.0.1
