server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Activity6CustomerDb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoint:
    web:
      exposure:
        include: health,info