server:
  port: 8083


spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: pass
    virtual-host: /

  app:
    rabbit:
      exchange: orders.exchange
      queue: orders.notification
      routing-key: orders.created

eureka:
  client:
     Service-url:
      defaultZone: http://discovery-server:8761/eureka

management:
  endpoint:
    web:
      exposure:
        include: health,info