server:
  port: 8083


spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: pass
    virtual-host: /

  eureka:
    client:
      Service-url:
        defaultZone: http://api-gateway:8761/eureka

  app:
    rabbit:
      exchange: orders.exchange
      queue: orders.notification
      routing-key: orders.created

management:
  endpoint:
    web:
      exposure:
        include: health,info