server:
  port: 8082


spring:
  datasource:
    url: jdbc:postgresql://sqlserver:5432/orders
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: pass

product:
  base-url: http://product-service:8081

management:
 endpoint:
   web:
     exposure:
       include: health,info


